/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import tikets.Controlador;
import tikets.ticket;

/**
 *
 * @author Student
 */
public class FrmGenerador extends javax.swing.JFrame {

    /**
     * Creates new form FrmGenerador
     */
    private Controlador control;
    public FrmGenerador() {
        initComponents();
        disableOrActiveAll(false);
        control = new Controlador();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerarBtn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MenuLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PlataformaLbl = new javax.swing.JLabel();
        PreferLbl = new javax.swing.JLabel();
        CajaLbl = new javax.swing.JLabel();
        TipoLbl = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JTextField();
        TicketLbl = new javax.swing.JLabel();
        NumeroLbl = new javax.swing.JLabel();
        numeroTxt = new javax.swing.JTextField();

        GenerarBtn1.setBackground(new java.awt.Color(153, 153, 153));
        GenerarBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenerarBtn1.setText("Generar");
        GenerarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarBtn1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        MenuLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenuLbl.setForeground(new java.awt.Color(255, 255, 255));
        MenuLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLbl.setText("Menu Generar Tickets");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione el tipo de ticket");

        PlataformaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PlataformaLbl.setForeground(new java.awt.Color(255, 255, 255));
        PlataformaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlataformaLbl.setText("Generar Plataforma");
        PlataformaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlataformaLblMouseClicked(evt);
            }
        });

        PreferLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PreferLbl.setForeground(new java.awt.Color(255, 255, 255));
        PreferLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PreferLbl.setText("Generar Preferencial");
        PreferLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreferLblMouseClicked(evt);
            }
        });

        CajaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CajaLbl.setForeground(new java.awt.Color(255, 255, 255));
        CajaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CajaLbl.setText("Generar Caja");
        CajaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajaLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlataformaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PreferLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CajaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PlataformaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CajaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(PreferLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        TipoLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TipoLbl.setForeground(new java.awt.Color(102, 102, 102));
        TipoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TipoLbl.setText("Tipo:");

        tipoTxt.setBackground(new java.awt.Color(242, 242, 242));
        tipoTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTxtActionPerformed(evt);
            }
        });

        TicketLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TicketLbl.setForeground(new java.awt.Color(102, 102, 102));
        TicketLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TicketLbl.setText("Ticket Generado");

        NumeroLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NumeroLbl.setForeground(new java.awt.Color(102, 102, 102));
        NumeroLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumeroLbl.setText("Numero:");

        numeroTxt.setBackground(new java.awt.Color(242, 242, 242));
        numeroTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numeroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TicketLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TipoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(tipoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TicketLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(NumeroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(TipoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tipoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoTxtActionPerformed

    private void numeroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTxtActionPerformed

    private void GenerarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarBtn1ActionPerformed

    private void PlataformaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlataformaLblMouseClicked
        // TODO add your handling code here:
        ticket t = control.generar("P");
        this.numeroTxt.setText(String.valueOf(t.getNumero()));
        this.tipoTxt.setText(t.getTipo());
        disableOrActiveAll(true);
        
        
        
    }//GEN-LAST:event_PlataformaLblMouseClicked

    private void CajaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajaLblMouseClicked
        // TODO add your handling code here:
           ticket t =  control.generar("C");
          this.numeroTxt.setText(String.valueOf(t.getNumero()));
        this.tipoTxt.setText(t.getTipo());
         disableOrActiveAll(true);
        
    }//GEN-LAST:event_CajaLblMouseClicked

    private void PreferLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreferLblMouseClicked
        // TODO add your handling code here:
       ticket t =  control.generar("A");
        this.numeroTxt.setText(String.valueOf(t.getNumero()));
        this.tipoTxt.setText(t.getTipo());
         disableOrActiveAll(true);
        
        
    }//GEN-LAST:event_PreferLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGenerador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGenerador().setVisible(true);
            }
        });
    }
    public void disableOrActiveAll(boolean x){
         this.TicketLbl.setVisible(x);
        this.TicketLbl.setEnabled(x);
        this.NumeroLbl.setEnabled(x);
        this.NumeroLbl.setVisible(x);
        this.numeroTxt.setEnabled(x);
        this.numeroTxt.setVisible(x);
        this.TipoLbl.setEnabled(x);
        this.TipoLbl.setVisible(x);
        this.tipoTxt.setEnabled(x);
        this.tipoTxt.setVisible(x);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CajaLbl;
    private javax.swing.JButton GenerarBtn1;
    private javax.swing.JLabel MenuLbl;
    private javax.swing.JLabel NumeroLbl;
    private javax.swing.JLabel PlataformaLbl;
    private javax.swing.JLabel PreferLbl;
    private javax.swing.JLabel TicketLbl;
    private javax.swing.JLabel TipoLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextField tipoTxt;
    // End of variables declaration//GEN-END:variables
}
